"""chat backend, multi-factory credentials, rbac role removal

Revision ID: 2a6c241bc067
Revises: e2dc5a1d3385
Create Date: 2026-07-24 12:11:28.675932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a6c241bc067'
down_revision: Union[str, None] = 'e2dc5a1d3385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # chat_threads <-> chat_messages have a genuine circular FK (thread_id -> thread_id,
    # summarized_through_message_id -> chat_messages.id). Autogenerate can't order these —
    # create chat_threads first WITHOUT the summarized_through_message_id FK, create
    # chat_messages referencing it normally, then add the deferred FK via ALTER TABLE.
    op.create_table('chat_threads',
    sa.Column('thread_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project', sa.String(), nullable=False),
    sa.Column('investigation_id', sa.String(), nullable=True),
    sa.Column('claimed_by_user_email', sa.String(), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('summarized_through_message_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.investigation_id'], ),
    sa.ForeignKeyConstraint(['project'], ['project_metadata.project'], ),
    sa.PrimaryKeyConstraint('thread_id'),
    sa.UniqueConstraint('investigation_id')
    )
    op.create_index(op.f('ix_chat_threads_claimed_by_user_email'), 'chat_threads', ['claimed_by_user_email'], unique=False)
    op.create_index(op.f('ix_chat_threads_project'), 'chat_threads', ['project'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('thread_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.thread_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_foreign_key(
        'fk_chat_threads_summarized_through_message_id', 'chat_threads', 'chat_messages',
        ['summarized_through_message_id'], ['id'],
    )
    op.create_table('resource_snapshot_blobs',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    op.create_table('project_factories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project', sa.String(), nullable=False),
    sa.Column('resource_group', sa.String(), nullable=False),
    sa.Column('factory_name', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('subscription_id', sa.String(), nullable=True),
    sa.Column('key_vault_uri', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['project_metadata.project'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project', 'factory_name', name='uq_project_factories_project_factory')
    )
    op.create_index(op.f('ix_project_factories_project'), 'project_factories', ['project'], unique=False)
    op.create_table('resource_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('state_name', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('blob_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(action = 'create' AND blob_hash IS NULL) OR (action = 'exists' AND blob_hash IS NOT NULL)", name='ck_resource_snapshots_blob_hash_nullability'),
    sa.CheckConstraint("action IN ('exists','create')", name='ck_resource_snapshots_action'),
    sa.CheckConstraint("kind IN ('pipeline','dataset','linked_service','data_flow','trigger','global_parameter')", name='ck_resource_snapshots_kind'),
    sa.ForeignKeyConstraint(['blob_hash'], ['resource_snapshot_blobs.hash'], ),
    sa.ForeignKeyConstraint(['project'], ['project_metadata.project'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project', 'kind', 'resource_name', 'sequence', name='uq_resource_snapshots_identity')
    )
    op.create_table('user_project_access',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('project', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project'], ['project_metadata.project'], ),
    sa.PrimaryKeyConstraint('user_email', 'project')
    )
    op.create_table('resource_snapshot_cursor',
    sa.Column('project', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('resource_name', sa.String(), nullable=False),
    sa.Column('current_sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project', 'kind', 'resource_name', 'current_sequence'], ['resource_snapshots.project', 'resource_snapshots.kind', 'resource_snapshots.resource_name', 'resource_snapshots.sequence'], name='fk_resource_snapshot_cursor_points_into_snapshots'),
    sa.PrimaryKeyConstraint('project', 'kind', 'resource_name')
    )
    op.drop_table('user_roles')
    op.create_foreign_key(None, 'audit_log', 'investigations', ['investigation_id'], ['investigation_id'])
    op.drop_column('audit_log', 'role')
    op.add_column('investigations', sa.Column('factory_name', sa.String(), nullable=True))
    op.add_column('investigations', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_investigations_project_factory', 'investigations', 'project_factories', ['project', 'factory_name'], ['project', 'factory_name'])
    op.create_unique_constraint('uq_project_contacts_project_type', 'project_contacts', ['project', 'contact_type'])
    op.add_column('project_metadata', sa.Column('platform', sa.String(), nullable=True))
    op.drop_column('project_metadata', 'adf_factory_name')
    op.drop_column('project_metadata', 'adf_client_id')
    op.drop_column('project_metadata', 'adf_resource_group')
    op.drop_column('project_metadata', 'adf_tenant_id')
    op.drop_column('project_metadata', 'adf_subscription_id')
    op.drop_column('project_metadata', 'key_vault_uri')
    op.add_column('project_rca', sa.Column('error_code', sa.String(), nullable=True))
    op.add_column('project_rca', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_project_rca_error_code'), 'project_rca', ['error_code'], unique=False)
    op.create_unique_constraint('uq_project_rca_pipeline_project_signature', 'project_rca', ['pipeline_id', 'project', 'error_signature'])
    op.add_column('rbac_permissions', sa.Column('requires_consent', sa.Boolean(), server_default='true', nullable=False))
    op.drop_index(op.f('ix_rbac_permissions_role'), table_name='rbac_permissions')
    op.drop_constraint(op.f('rbac_permissions_role_tool_name_key'), 'rbac_permissions', type_='unique')
    # Autogenerate doesn't reliably detect PK changes: model moved from a surrogate `id` PK
    # to `tool_name` as the PK directly. Drop the old PK before dropping `id` (can't drop a
    # column that's still part of a constraint), then establish the new one.
    op.drop_constraint('rbac_permissions_pkey', 'rbac_permissions', type_='primary')
    op.drop_column('rbac_permissions', 'id')
    op.drop_column('rbac_permissions', 'role')
    op.create_primary_key('rbac_permissions_pkey', 'rbac_permissions', ['tool_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Mirror of the upgrade()'s manual PK swap — drop the tool_name PK before re-adding id/role.
    op.drop_constraint('rbac_permissions_pkey', 'rbac_permissions', type_='primary')
    op.add_column('rbac_permissions', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False, server_default='investigator'))
    op.add_column('rbac_permissions', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.create_primary_key('rbac_permissions_pkey', 'rbac_permissions', ['id'])
    op.create_unique_constraint(op.f('rbac_permissions_role_tool_name_key'), 'rbac_permissions', ['role', 'tool_name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_rbac_permissions_role'), 'rbac_permissions', ['role'], unique=False)
    op.drop_column('rbac_permissions', 'requires_consent')
    op.drop_constraint('uq_project_rca_pipeline_project_signature', 'project_rca', type_='unique')
    op.drop_index(op.f('ix_project_rca_error_code'), table_name='project_rca')
    op.drop_column('project_rca', 'updated_at')
    op.drop_column('project_rca', 'error_code')
    op.add_column('project_metadata', sa.Column('key_vault_uri', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('project_metadata', sa.Column('adf_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('project_metadata', sa.Column('adf_tenant_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('project_metadata', sa.Column('adf_resource_group', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('project_metadata', sa.Column('adf_client_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('project_metadata', sa.Column('adf_factory_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('project_metadata', 'platform')
    op.drop_constraint('uq_project_contacts_project_type', 'project_contacts', type_='unique')
    op.drop_constraint('fk_investigations_project_factory', 'investigations', type_='foreignkey')
    op.drop_column('investigations', 'updated_at')
    op.drop_column('investigations', 'factory_name')
    op.add_column('audit_log', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.create_table('user_roles',
    sa.Column('upn', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('upn', name=op.f('user_roles_pkey'))
    )
    op.drop_table('resource_snapshot_cursor')
    op.drop_table('user_project_access')
    op.drop_table('resource_snapshots')
    op.drop_index(op.f('ix_project_factories_project'), table_name='project_factories')
    op.drop_table('project_factories')
    op.drop_table('resource_snapshot_blobs')
    op.drop_constraint('fk_chat_threads_summarized_through_message_id', 'chat_threads', type_='foreignkey')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_threads_project'), table_name='chat_threads')
    op.drop_index(op.f('ix_chat_threads_claimed_by_user_email'), table_name='chat_threads')
    op.drop_table('chat_threads')
    # ### end Alembic commands ###
