"""initial schema

Revision ID: 5c8acdf31a54
Revises: 
Create Date: 2026-07-21 12:25:59.861306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8acdf31a54'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('audit_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('project', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_audit_log_investigation_id'), 'audit_log', ['investigation_id'], unique=False)
    op.create_table('project_metadata',
    sa.Column('project', sa.String(), nullable=False),
    sa.Column('criticality', sa.String(), nullable=False),
    sa.Column('depends_on', sa.String(), nullable=True),
    sa.Column('key_vault_uri', sa.String(), nullable=True),
    sa.Column('adf_tenant_id', sa.String(), nullable=True),
    sa.Column('adf_client_id', sa.String(), nullable=True),
    sa.Column('adf_subscription_id', sa.String(), nullable=True),
    sa.Column('adf_resource_group', sa.String(), nullable=True),
    sa.Column('adf_factory_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('project')
    )
    op.create_table('rbac_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'tool_name')
    )
    op.create_index(op.f('ix_rbac_permissions_role'), 'rbac_permissions', ['role'], unique=False)
    op.create_table('user_roles',
    sa.Column('upn', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('upn')
    )
    op.create_table('investigations',
    sa.Column('investigation_id', sa.String(), nullable=False),
    sa.Column('project', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('pipeline_name', sa.String(), nullable=False),
    sa.Column('run_status', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_detail', sa.JSON(), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('diagnosis_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project'], ['project_metadata.project'], ),
    sa.PrimaryKeyConstraint('investigation_id')
    )
    op.create_index(op.f('ix_investigations_project'), 'investigations', ['project'], unique=False)
    op.create_table('project_contacts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project', sa.String(), nullable=False),
    sa.Column('contact_type', sa.String(), nullable=False),
    sa.Column('assigned_user_email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['project_metadata.project'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_contacts_project'), 'project_contacts', ['project'], unique=False)
    op.create_table('project_rca',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('project', sa.String(), nullable=False),
    sa.Column('error_signature', sa.String(), nullable=False),
    sa.Column('error_category', sa.String(), nullable=False),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('criticality', sa.String(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('fix_applied', sa.Text(), nullable=True),
    sa.Column('preventive_steps', sa.Text(), nullable=True),
    sa.Column('invocation_count', sa.Integer(), nullable=False),
    sa.Column('last_failure_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('denial_history', sa.JSON(), nullable=False),
    sa.Column('last_rerun_attempt', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['project_metadata.project'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_rca_pipeline_id'), 'project_rca', ['pipeline_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_rca_pipeline_id'), table_name='project_rca')
    op.drop_table('project_rca')
    op.drop_index(op.f('ix_project_contacts_project'), table_name='project_contacts')
    op.drop_table('project_contacts')
    op.drop_index(op.f('ix_investigations_project'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_rbac_permissions_role'), table_name='rbac_permissions')
    op.drop_table('rbac_permissions')
    op.drop_table('project_metadata')
    op.drop_index(op.f('ix_audit_log_investigation_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
