"""drop criticality and depends_on

Revision ID: e2dc5a1d3385
Revises: 5c8acdf31a54
Create Date: 2026-07-21 14:29:29.137399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2dc5a1d3385'
down_revision: Union[str, None] = '5c8acdf31a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_metadata', 'depends_on')
    op.drop_column('project_metadata', 'criticality')
    op.drop_column('project_rca', 'criticality')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_rca', sa.Column('criticality', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('project_metadata', sa.Column('criticality', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('project_metadata', sa.Column('depends_on', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
